name: Build Electron App
on:
  push:
    tags:
      - 'v*'

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Import Apple Developer Certificate
        env:
          MAC_CERTIFICATE: ${{ secrets.MAC_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        run: |
          echo "$MAC_CERTIFICATE" | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
          security find-identity -v

      - name: Install dependencies
        run: npm install

      - name: Resign modules
        run: npm run resign

      - name: Build Electron App for Mac
        run: npm run build && npm run build:mac
        env:
          CSC_NAME: "Jan Vincent Lunge (BLH4PG2L7J)"
          CSC_KEYCHAIN: build.keychain

      - name: Upload Mac Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-app
          path: dist/*.dmg
          compression-level: 0

